### PR TITLE
feat: add a lot of color overrides

### LINKED ISSUE #66: Font color is not distinguishable
swappy-20231229_153246

This is pretty new, I think has been introduced alongside #64 but I haven't confirmed yet.

### PR DESCRIPTION
**Pull request by mrtnvgr**
Fixes #66 

##### TODO

- [ ] Devtools
- [ ] Buttons, checkboxes in context menus
- [ ] "Floating" windows in `about:preferences`
- [x] Primary color in search popup
- ...

### CODE REVIEW

**Comment by mrtnvgr** [comment]
Also `help-wanted` tag

**Comment by mrtnvgr** [comment]
It seems that all other colors are secured by `:host`. We really need something better than a whole bunch of overrides, but I guess it's okay for now. Please review :)

**Review by NotAShelf — COMMENTED** [review]
Looks good, I'll test this once I am on my workstation but until then if you could squash all commits into one that would be appreciated.

**Review by NotAShelf — APPROVED** [review]
LGTM

**Comment by NotAShelf** [comment]
CC: @sioodmy for review

**Review by sioodmy — APPROVED** [review]

**Comment by NotAShelf** [comment]
thanks @mrtnvgr !

**Pull request merged**
