### PR TITLE
chore: use `mkOption` for `extensions.darkreader.enable`

### PR DESCRIPTION
**Pull request by mrtnvgr**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by sioodmy** [comment]
Can you explain why would we use anything different than mkEnableOption for option called `darkreader.enable`?

**Comment by mrtnvgr** [comment]
> Can you explain why would we use anything different than mkEnableOption for option called `darkreader.enable`?

As I understood, darkreader extension is enabled by default, so `mkOption` will be better for that task, because it allows you to set the default value.

**Comment by mrtnvgr** [comment]
I think it looks better with `mkOption`, maybe that's too much of a nit pick.

**Comment by NotAShelf** [comment]
I think this is redundant. mkEnableOption is just an abstraction over mkOption with the type bool.

**Pull request closed without merging**
