### PR TITLE
refactor: restructure some options

### PR DESCRIPTION
**Pull request by mrtnvgr**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Preparation for another PR

### CODE REVIEW

**Review by sioodmy — APPROVED** [review]

**Comment by sioodmy** [comment]
and we got our first merge conflicts...

**Comment by mrtnvgr** [comment]
@sioodmy all fixed

**Review by sioodmy — APPROVED** [review]

**Comment by mrtnvgr** [comment]
@sioodmy why this is "breaking-change", isn't `modules/hm/options/renamed.nix` enough?

**Comment by sioodmy** [comment]
> @sioodmy why is this a "breaking-change", isn't `modules/hm/options/renamed.nix` enough?

I'm pretty sure renaming existing options can be considered as breaking-change. It's just a PR label, nothing serious.

**Pull request merged**
