### PR TITLE
Security & Privacy Tweaks

### PR DESCRIPTION
**Pull request by NotAShelf**
TODO:

- [ ] Disable JS by default. JS sucks, but a lot of websites still require it - therefore an option to toggle it will be in the configuration options.

- [ ] Switch default search engine to searx.be. Additionally, we may look into hosting our own searx instance.

- [ ] Tweak user.js to include the most important part of arkenfox's tweaks. We already borrow a lot, but it would not hurt to revisit our user.js

- [x] Cull default addons to just uBlock and Dark reader. Move rest of the addons to a togglable extraAddons attribute set that is disabled by default.

### CODE REVIEW

**Comment by NotAShelf** [comment]
@W-Y-R I'm still a bit on the fence about disabling Javascript by default. It really does suck, but a browser configuration that disables Javascript is mostly unusable on a day to day basis. Seeing we currently lack any form of documentation (and free time by maintainers) I am not sure if I want to send a lot of users looking for answers to why some websites don't work.

Should we perhaps leave JS enabled by default, but allow the user to disable it with a simple toggle if that better serves their use-case?

**Comment by W-Y-R** [comment]
I understand your reasoning regarding JavaScript and I take no issue with enabling it by default. My only suggestion would be creating an option in the module for this exact purpose.
`javaScript.enable = true/false;`

**Comment by jh-devv** [comment]
> TODO:
>    - Tweak user.js to include the most important part of arkenfox's tweaks. We already borrow a lot, but it would not hurt to revisit our user.js

There is an flake for this which you could do this:
```nix
{
  programs.firefox = {
    enable = true;
    arkenfox = {
      enable = true;
      version = "103.0";
    };
    
    profiles.Default.arkenfox = {
      enable = true;
      "0000".enable = true;
      "0001" = {
        enable = true;
        "0101"."browser.shell.checkDefaultBrowser".value = true;
      };
      "0002" = {
        enable = true;
        "0204"."browser.search.region".enable = true;
      };
    };
  };
}
```
This would not be probably so hard to implement for Schizofox?

**Comment by jh-devv** [comment]
> @W-Y-R I'm still a bit on the fence about disabling Javascript by default. It really does suck, but a browser configuration that disables Javascript is mostly unusable on a day to day basis. Seeing we currently lack any form of documentation (and free time by maintainers) I am not sure if I want to send a lot of users looking for answers to why some websites don't work.
> 
> Should we perhaps leave JS enabled by default, but allow the user to disable it with a simple toggle if that better serves their use-case?

Why not just disable Ion and JIT? 
> Looking at CVE (Common Vulnerabilities and Exposures) data after 2019 shows that roughly 45% of CVEs issued for V8 were related to the JIT engine.
> Source: https://microsoftedge.github.io/edgevr/posts/Super-Duper-Secure-Mode/
This is not about Firefox and Gecko, but still?

**Comment by NotAShelf** [comment]
Do keep in mind that Schizofox is not yet another "Firefox with arjenfox user.js" distribution. It is an opinionated configuration framework with a focus on privacy and security - and I think borrowing policies from a middleman (a flake for arkenfox policies, for example) compromises on this goal. For the foreseeable future, I'll be maintaining our own policy file as defined by schizofox.settings.

> Why not just disable Ion and JIT?
>
>  >Looking at CVE (Common Vulnerabilities and Exposures) data after 2019 shows that roughly 45% of CVEs issued for V8 were related to the JIT engine.
>  >Source: microsoftedge.github.io/edgevr/posts/Super-Duper-Secure-Mode
> This is not about Firefox and Gecko, but still?

If you have a similar resource, but for *Firefox and Gecko* then I would be happy to read it. Becauase Edge is yet another Chromium fork:tm: and has varying differences with Firefox and therefore Schizofox.

**Comment by jh-devv** [comment]
> Do keep in mind that Schizofox is not yet another "Firefox with arjenfox user.js" distribution. It is an opinionated configuration framework with a focus on privacy and security - and I think borrowing policies from a middleman (a flake for arkenfox policies, for example) compromises on this goal. For the foreseeable future, I'll be maintaining our own policy file as defined by schizofox.settings.

Don't we currently just basically copy them from Arkenfox and add __some__ of our?

The Arkenfox flake seems to not set any defaults, if you enable all the sections you can, that would be just the same as Arkefox'es `user.js`, but with nix syntax? They seem to just download the `user.js`, automatically write `nix config toggles` for them, and then just expose that. Which we can do without that said flake?

**Comment by jh-devv** [comment]
> > Why not just disable Ion and JIT?
> > > Looking at CVE (Common Vulnerabilities and Exposures) data after 2019 shows that roughly 45% of CVEs issued for V8 were related to the JIT engine.
> > > Source: microsoftedge.github.io/edgevr/posts/Super-Duper-Secure-Mode
> > > This is not about Firefox and Gecko, but still?
> 
> If you have a similar resource, but for _Firefox and Gecko_ then I would be happy to read it. Becauase Edge is yet another Chromium fork:tm: and has varying differences with Firefox and therefore Schizofox.

https://www.tenable.com/cve/search?q=Firefox+jit&sort=&page=1
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=firefox+jit
There exists at least *some* CVE's for JIT

**Comment by HPsaucii** [comment]
wanted to give my own six pence on the subject, i currently have a firefox setup that utilizes the "important" parts of arkenfox (written in pure nix, yes, this did take me ages)
`
"browser.aboutConfig.showWarning" = false;
"browser.newtabpage.activity-stream.showSponsored" = false;
"browser.newtabpage.activity-stream.showSponsoredTopSites" = false;
"browser.newtabpage.activity-stream.default.sites" = "";
"geo.provider.network.url" = "https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%";
"geo.provider.use_gpsd" = false;
"geo.provider.use_geoclue" = false;
"extensions.getAddons.showPane" = false;
"extensions.htmlaboutaddons.recommendations.enabled" = false;
"browser.discovery.enabled" = false;
"browser.shopping.experience2023.enabled" = false;
"datareporting.policy.dataSubmissionEnabled" = false;
"datareporting.healthreport.uploadEnabled" = false;
"toolkit.telemetry.unified" = false;
"toolkit.telemetry.enabled" = false; 
"toolkit.telemetry.server" = "data:,";
"toolkit.telemetry.archive.enabled" = false;
"toolkit.telemetry.newProfilePing.enabled" = false; 
"toolkit.telemetry.shutdownPingSender.enabled" = false; 
"toolkit.telemetry.updatePing.enabled" = false; 
"toolkit.telemetry.bhrPing.enabled" = false; 
"toolkit.telemetry.firstShutdownPing.enabled" = false; 
"toolkit.telemetry.coverage.opt-out" = true; 
"toolkit.coverage.opt-out" = true; 
"toolkit.coverage.endpoint.base" = "";
"browser.ping-centre.telemetry" = false;
"browser.newtabpage.activity-stream.feeds.telemetry" = false;
"browser.newtabpage.activity-stream.telemetry" = false;
"app.shield.optoutstudies.enabled" = false;
"app.normandy.enabled" = false;
"app.normandy.api_url" = "";
"breakpad.reportURL" = "";
"browser.tabs.crashReporting.sendReport" = false; 
"browser.crashReports.unsubmittedCheck.enabled" = false; 
"browser.crashReports.unsubmittedCheck.autoSubmit2" = false; 
"captivedetect.canonicalURL" = "";
"network.captive-portal-service.enabled" = false; 
"network.connectivity-service.enabled" = false;
"browser.safebrowsing.malware.enabled" = false;
"browser.safebrowsing.phishing.enabled" = false;
"browser.safebrowsing.downloads.enabled" = false;
"browser.safebrowsing.downloads.remote.enabled" = false;
"browser.safebrowsing.downloads.remote.url" = ""; 
"browser.safebrowsing.downloads.remote.block_potentially_unwanted" = false;
"browser.safebrowsing.downloads.remote.block_uncommon" = false;
"browser.safebrowsing.allowOverride" = false;
"network.prefetch-next" = false;
"network.dns.disablePrefetch" = true;
"network.dns.disablePrefetchFromHTTPS" = true; 
"network.predictor.enabled" = false;
"network.predictor.enable-prefetch" = false; 
"network.http.speculative-parallel-limit" = 0;
"browser.places.speculativeConnect.enabled" = false;
"browser.send_pings" = false; 
"network.proxy.socks_remote_dns" = true;
"network.file.disable_unc_paths" = true; 
"network.gio.supported-protocols" = ""; 
"network.proxy.failover_direct" = false;
"network.proxy.allow_bypass" = false;
"browser.urlbar.speculativeConnect.enabled" = false;
"browser.urlbar.suggest.quicksuggest.nonsponsored" = false; 
"browser.urlbar.suggest.quicksuggest.sponsored" = false; 
"browser.search.suggest.enabled" = false;
"browser.urlbar.suggest.searches" = false;
"browser.urlbar.trending.featureGate" = false;
"browser.urlbar.addons.featureGate" = false; 
"browser.urlbar.mdn.featureGate" = false; 
"browser.urlbar.pocket.featureGate" = false; 
"browser.urlbar.weather.featureGate" = false; 
"browser.urlbar.clipboard.featureGate" = false; 
"browser.formfill.enable" = false;
"browser.urlbar.suggest.engines" = false;
"layout.css.visited_links_enabled" = false;
"browser.search.separatePrivateDefault" = true; 
"browser.search.separatePrivateDefault.ui.enabled" = true; 
"signon.autofillForms" = false;
"signon.formlessCapture.enabled" = false;
"network.auth.subresource-http-auth-allow" = 1;
"browser.cache.disk.enable" = false;
"browser.privatebrowsing.forceMediaMemoryCache" = true; 
"media.memory_cache_max_size" = 65536;
"browser.sessionstore.privacy_level" = 2;
"security.ssl.require_safe_negotiation" = true;
"security.tls.enable_0rtt_data" = false;
"security.OCSP.enabled" = 1; 
"security.OCSP.require" = true;
"security.cert_pinning.enforcement_level" = 2;
"security.remote_settings.crlite_filters.enabled" = true;
"security.pki.crlite_mode" = 2;
"security.mixed_content.block_display_content" = true; 
"dom.security.https_only_mode" = true; 
"dom.security.https_only_mode_pbm" = true; 
"dom.security.https_only_mode.upgrade_local" = true;
"dom.security.https_only_mode_send_http_background_request" = false;
"security.ssl.treat_unsafe_negotiation_as_broken" = true;
"browser.xul.error_pages.expert_bad_cert" = true;
"network.http.referer.XOriginTrimmingPolicy" = 2;
"privacy.userContext.enabled" = true;
"privacy.userContext.ui.enabled" = true;
"privacy.userContext.newTabContainerOnLeftClick.enabled" = true;
"media.peerconnection.ice.proxy_only_if_behind_proxy" = true;
"media.peerconnection.ice.default_address_only" = true;
"media.peerconnection.ice.no_host" = true;
"media.gmp-provider.enabled" = false;
"dom.disable_window_move_resize" = true;
"browser.download.start_downloads_in_tmp_dir" = true; 
"browser.helperApps.deleteTempFileOnExit" = true;
"browser.uitour.enabled" = false;
"browser.uitour.url" = ""; 
"devtools.debugger.remote-enabled" = false; 
"permissions.default.shortcuts" = 2;
"permissions.manager.defaultsUrl" = "";
"webchannel.allowObject.urlWhitelist" = "";
"network.IDN_show_punycode" = true;
"pdfjs.disabled" = false; 
"pdfjs.enableScripting" = false; 
"browser.tabs.searchclipboardfor.middleclick" = false; 
"browser.download.useDownloadDir" = false;
"browser.download.alwaysOpenPanel" = false;
"browser.download.manager.addToRecentDocs" = false;
"browser.download.always_ask_before_handling_new_types" = true;
"extensions.enabledScopes" = 5; 
"extensions.autoDisableScopes" = 15; 
"extensions.postDownloadThirdPartyPrompt" = false;
"extensions.webextensions.restrictedDomains" = "";
"browser.contentblocking.category" = "strict"; 
"privacy.antitracking.enableWebcompat" = false;
"privacy.sanitize.sanitizeOnShutdown" = true;
"privacy.clearOnShutdown.cache" = true;     
"privacy.clearOnShutdown.downloads" = true; 
"privacy.clearOnShutdown.formdata" = true;  
"privacy.clearOnShutdown.history" = true;   
"privacy.clearOnShutdown.sessions" = true;  
"privacy.clearOnShutdown.siteSettings" = false; 
"privacy.clearOnShutdown.openWindows" = true;
"privacy.clearOnShutdown.cookies" = true; 
"privacy.clearOnShutdown.offlineApps" = true; 
"privacy.cpd.cache" = true;    
"privacy.cpd.formdata" = true; 
"privacy.cpd.history" = true;  
"privacy.cpd.sessions" = true; 
"privacy.cpd.offlineApps" = false; 
"privacy.cpd.cookies" = false;
"privacy.cpd.openWindows" = false; 
"privacy.cpd.passwords" = false;
"privacy.cpd.siteSettings" = false;
"privacy.sanitize.timeSpan" = 0;
"privacy.resistFingerprinting" = true; 
"privacy.resistFingerprinting.pbmode" = true; 
"privacy.window.maxInnerWidth" = 1600;
"privacy.window.maxInnerHeight" = 900;
"privacy.resistFingerprinting.block_mozAddonManager" = true;
"privacy.resistFingerprinting.letterboxing" = true; 
"privacy.resistFingerprinting.letterboxing.dimensions" = ""; 
"privacy.resistFingerprinting.exemptedDomains" = "*.example.invalid";
"browser.display.use_system_colors" = true; 
"widget.non-native-theme.enabled" = true; 
"browser.link.open_newwindow" = 3; 
"browser.link.open_newwindow.restriction" = 0;
"webgl.disabled" = true;
"browser.privatebrowsing.autostart" = true;
"browser.cache.memory.enable" = false;
"browser.cache.memory.capacity" = 0;
"signon.rememberSignons" = false;
"permissions.memory_only" = true; 
"security.nocertdb" = true;
"browser.chrome.site_icons" = false;
"browser.sessionstore.max_tabs_undo" = 0;
"browser.sessionstore.resume_from_crash" = false;
"browser.download.forbid_open_with" = true;
"browser.urlbar.suggest.history" = false;
"browser.urlbar.suggest.bookmark" = false;
"browser.urlbar.suggest.openpage" = false;
"browser.urlbar.suggest.topsites" = false; 
"browser.urlbar.maxRichResults" = 0;
"browser.urlbar.autoFill" = false;
"places.history.enabled" = false;
"browser.download.folderList" = 2;
"extensions.formautofill.addresses.enabled" = false; 
"extensions.formautofill.creditCards.enabled" = false; 
"dom.popup_allowed_events" = "click dblclick mousedown pointerdown";
"browser.pagethumbnails.capturing_disabled" = true; 
"keyword.enabled" = false;
"mathml.disabled" = true; 
"svg.disabled" = false; 
"gfx.font_rendering.graphite.enabled" = false;
"javascript.options.asmjs" = false;
"javascript.options.ion" = false;
"javascript.options.baselinejit" = false;
"javascript.options.jit_trustedprincipals" = true; 
"javascript.options.wasm" = false;
"gfx.font_rendering.opentype_svg.enabled" = false;
"media.eme.enabled" = false;
"browser.eme.ui.enabled" = false;
"network.dns.disableIPv6" = true;
"network.http.referer.XOriginPolicy" = 2;
"network.trr.bootstrapAddr" = "10.0.0.1"; 
"extensions.blocklist.enabled" = true; 
"network.http.referer.spoofSource" = false; 
"security.dialog_enable_delay" = 1000; 
"privacy.firstparty.isolate" = false; 
"extensions.webcompat.enable_shims" = true; 
"security.tls.version.enable-deprecated" = false; 
"extensions.webcompat-reporter.enabled" = false; 
"extensions.quarantinedDomains.enabled" = true; 
`

**Comment by NotAShelf** [comment]
Closing in favor of #110. Anyone's welcome to contribute their ideas under the new PR, as I will be taking a closer look at privacy related reworks over the following week.

**Pull request closed without merging**
