### PR TITLE
fix: remove deprecated .desktop category

### PR DESCRIPTION
**Pull request by diniamo**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Other (please describe): remove deprecated code

## What is the current behavior?

`Application` category is included in the generated desktop file.

Issue Number: N/A

## What is the new behavior?

It is not.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

No, since nothing should rely on the application category, since it has already been deprecated.

### CODE REVIEW

**Comment by NotAShelf** [comment]
Merging once the CI passes.

As a side note, I probably want to expose keywords and categories as module options (internal nor not). Might look at that after this has been merged.

**Comment by NotAShelf** [comment]
Thanks :)

**Comment by diniamo** [comment]
> Merging once the CI passes.
> 
> As a side note, I probably want to expose keywords and categories as module options (internal nor not). Might look at that after this has been merged.

Why?

**Comment by NotAShelf** [comment]
Mostly to make it *at least* an accessible interface.

**Pull request merged**
