### PR TITLE
WIP feat: support derivatives

### PR DESCRIPTION
**Pull request by nyawox**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

WIP. Successfully installed but still have to implement option to change .mozilla path

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?
Hopefully it won't
- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by NotAShelf — APPROVED** [review]
LGTM!

**Comment by nyawox** [comment]
Finally figured out why it wasn't working: `configPath` wasn't included in the sandbox xd

The solution is simple: adding the `configPath` to `bindrw` works. 
I'm uncertain if replacing `.mozilla` with `configPath` breaks anything tho.

I'm considering implementing an option to add extra directories to the sandbox. 
In any case, sooner or later, probably I would have made a separate PR for my tridactyl use case.

**Comment by surfaceflinger** [comment]
Worth noting that some policies are exclusive to Firefox ESR and I wonder if these are available too in eg. Floorp since it's based on ESR.

**Comment by nyawox** [comment]
> Worth noting that some policies are exclusive to Firefox ESR and I wonder if these are available too in eg. Floorp since it's based on ESR.

I remembered there was a weird issue that `extraPolicies` doesn't work with floorp anyways, and also found few people with same issue, saying policies.json doesn't work on their discord with none solution. I might give up and close the pr, rather try to implement some other features I want like nativeMessagingHosts, extraSandboxDirectories. Implementing nativeMessagingHosts should be pretty straight forward.

**Pull request closed without merging**
